// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetMatcher.Api.Data;

#nullable disable

namespace PetMatcher.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606214216_SeedPetsData")]
    partial class SeedPetsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PetMatcher.Api.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightInLbs")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Golden Retriever",
                            Color = "Golden",
                            IsVaccinated = true,
                            Name = "Max",
                            Personality = "Friendly, energetic, and highly social",
                            Species = "Dog",
                            WeightInLbs = 65.400000000000006
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Breed = "Siamese",
                            Color = "Seal Point",
                            IsVaccinated = true,
                            Name = "Luna",
                            Personality = "Vocal, affectionate, and demanding of attention",
                            Species = "Cat",
                            WeightInLbs = 8.5
                        },
                        new
                        {
                            Id = 3,
                            Age = 1,
                            Breed = "French Bulldog",
                            Color = "Brindle",
                            IsVaccinated = true,
                            Name = "Charlie",
                            Personality = "Playful couch potato, loves naps and treats",
                            Species = "Dog",
                            WeightInLbs = 22.100000000000001
                        },
                        new
                        {
                            Id = 4,
                            Age = 5,
                            Breed = "Labrador Retriever",
                            Color = "Black",
                            IsVaccinated = true,
                            Name = "Bella",
                            Personality = "Loyal, gentle, and excellent swimmers",
                            Species = "Dog",
                            WeightInLbs = 72.0
                        },
                        new
                        {
                            Id = 5,
                            Age = 4,
                            Breed = "Domestic Shorthair",
                            Color = "Tabby",
                            IsVaccinated = true,
                            Name = "Oliver",
                            Personality = "Calm, independent, but loves a good chin scratch",
                            Species = "Cat",
                            WeightInLbs = 11.199999999999999
                        },
                        new
                        {
                            Id = 6,
                            Age = 1,
                            Breed = "Bengal",
                            Color = "Spotted Rosette",
                            IsVaccinated = false,
                            Name = "Milo",
                            Personality = "High energy, highly intelligent, and loves water",
                            Species = "Cat",
                            WeightInLbs = 10.6
                        },
                        new
                        {
                            Id = 7,
                            Age = 2,
                            Breed = "Beagle",
                            Color = "Tricolor",
                            IsVaccinated = true,
                            Name = "Daisy",
                            Personality = "Curious, driven by scent, and very vocal",
                            Species = "Dog",
                            WeightInLbs = 24.5
                        },
                        new
                        {
                            Id = 8,
                            Age = 4,
                            Breed = "German Shepherd",
                            Color = "Black and Tan",
                            IsVaccinated = true,
                            Name = "Rocky",
                            Personality = "Protective, disciplined, and quick to learn",
                            Species = "Dog",
                            WeightInLbs = 83.099999999999994
                        },
                        new
                        {
                            Id = 9,
                            Age = 7,
                            Breed = "Persian",
                            Color = "White",
                            IsVaccinated = true,
                            Name = "Cleo",
                            Personality = "Quiet, dignified, and prefers a peaceful home",
                            Species = "Cat",
                            WeightInLbs = 9.0
                        },
                        new
                        {
                            Id = 10,
                            Age = 6,
                            Breed = "Chihuahua",
                            Color = "Fawn",
                            IsVaccinated = true,
                            Name = "Coco",
                            Personality = "Feisty, fiercely loyal to one person, alert",
                            Species = "Dog",
                            WeightInLbs = 5.2999999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
